### ISSUE TITLE
Support for/Examples of long-running instances?

### ISSUE THREAD

**Issue by joshstrange** [MauriceConrad/iCloud-API#10]
Not an issue as much as a question. Do you or anyone else have experience with a long-running instance of this? What I means is should I tear down my iCloud instance each time or reuse it? I am sharing session but I have a nodejs process that I am writing to be able to query it's data via voice (Alexa skill) or other UI/CLI tools. 

I am planning on polling the FmF endpoints every 1-2 minutes so I can write some code to determine location of my partner and I for geo-related things ("X in on the way home", "Y remember to do Z", Turn off all lights when we both leave, etc). I can keep calling the getLocations() method but I didn't know if there was any "Session validity"/"Session expiration" checking and/or if it would refresh/renew the session if it had expired. 

My guess is that it won't work and I should just re-use the session but recreate the iCloud instance to force-rechecking. That plus some system to re-enter my 2FA code remotely (maybe web endpoint with simple form that get's texted to me when it's needed? How is everyone else handling this, even for cron-type jobs this would be an issue right?).

**Comment by MauriceConrad** [comment]
I do not know but you CAN turn down it often as you want. You just should store your session anywhere, e.g. in a file.

**Comment by bstrebel** [comment]
I am also very interested in this issue! Yes, you can restart the iCloud connection but unfortunately an email is send to your Apple account if you re-login after running into the code 11 error after 15 minutes (see #6 for details).

**Comment by joeqread** [comment]
Easy/free way to get past the 2-factor:

Get a google voice number, link iCloud account to that phone number, npm install voice.js, trigger sending of code via sms, poll for sms messages until you find the one from apple with code in it.  Make g-mail filter to delete notifications from icloud about a new device login.
