### ISSUE TITLE
Upgraded Reminders don't seem to work

### ISSUE THREAD

**Issue by gbailey4** [MauriceConrad/iCloud-API#40]
When I try and use your demo code to pull the reminders I'm greeted by the two reminders that Apple inserts after you upgrade the reminders backend. Is there any way to pull post upgraded to iOS 13 reminders?

Reminders returned:
Array(2) ["Where are my reminders?", "The creator of this list has upgraded these remind…"]

* Edited to remove the "Test" reminder that I put in to make clearer

**Comment by MauriceConrad** [comment]
Fixed
