### ISSUE TITLE
Constant two-factor authentication notifications when playing sounds on iPhone

### ISSUE THREAD

**Issue by IceBotYT** [MauriceConrad/iCloud-API#62]
Hi there.
Every time I run this below:
```js
require("dotenv").config();

let username = process.env.ICLOUD_EMAIL;
let password = process.env.ICLOUD_PWD;

module.exports = function () {
  return new Promise(async (reso, reje) => {
    let myCloud = await require("./prompt-credentials")();
    let devices;
    try {
      devices = await myCloud.FindMe.get(username, password);
    } catch (e) {
      return reje(e);
    }

    const myPhone = devices.content[0];
    try {
      const res = await myCloud.FindMe.playSound(myPhone.id);
      reso(res);
    } catch (e) {
      reje(e);
    }
  });
};
```
It plays the sound, but I always get a notification saying that a new sign-in is happening from my server.
Is there any way to remedy this?

**Comment by IceBotYT** [comment]
I just ended up not using this library anymore

**Comment by Kryd0s** [comment]
For anyone who has the constant two factor authentication notifications and finds this, you need to save your session once you're logged in and answered the security question the first time. Also make sure that you have permissions to write to the session file and it's actually getting updated with the new information.
`myCloud.saveSession(sessionPath);`

**Comment by Kryd0s** [comment]
OP is probably long gone, but if anyone else has the constant two factor requests and finds this issue the solution is pretty simple. After you enter the two factor authentication code you need to save your session to a file, and then that same session, including the previous 6 digit code, will be used for future requests.
`myCloud.saveSession(sessionPath);`

**Comment by Kryd0s** [comment]
OP is probably long gone, but I was having the same issue and I think I've got it figured out now. It looks like the trick is after you do the `myCloud.FindMe.get();` you need to save your session again each time `myCloud.saveSession(sessionPath);` It's been working for like 15 minutes now without sending another two factor request so I think it's solved.

**Comment by IceBotYT** [comment]
Oh. I am not long gone, thank you for the solution! I use Home Assistant now though
